### ISSUE TITLE
[REQ] Implement Copa TODO Comment Features to extend functionality

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#611]
### What kind of request is this?

Tracking Issue for [lfx-mentorship](https://github.com/cncf/mentoring/tree/a002554cea031e901a09d583146727cc399a5394/programs/lfx-mentorship) Jun - Aug 2024 to be worked on by mentee.

### What is your request or suggestion?

The following copacetic features (currently listed as TODO comments) will enhance Copacetic user experience and extend its functionality. The issues range from adding custom image repos, to handling custom configuration at the package and system level.

- [x] #602 (investigate and document)
- [x] #596 , & #38 (investigated and will not be implementing support)
- [x] #595 
- [x] #389 
- [x] #190
- [x] #40
- [x] #147 (investigate)
- [x] #723
- [ ] #604
- [x] #651
- [x] #438
- [x] Remove ToDo comments from code

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

CC: @MiahaCybersec @RobertKielty

**Comment by officialasishkumar** [comment]
are there any pre tasks?

**Comment by ashnamehrotra** [comment]
Hi @officialasishkumar this is for the LFX mentorship program and will be worked on by @MiahaCybersec

**Comment by Atharva-Kanherkar** [comment]
> Hi @officialasishkumar this is for the LFX mentorship program and will be worked on by @MiahaCybersec

Anyone call apply there, right?

**Comment by m-rit** [comment]
Hi, I am planning to apply for this project in LFX mentorship. Is the project already assigned ?

**Comment by plasmium1** [comment]
I am super interested in helping with the copacetic features above, and am applying for this mentorship. I just went through the project CLI quick demo, and it is indeed a very useful tool. I love the usage of both golang and various shell script by copa CLI.

**Comment by ashnamehrotra** [comment]
@plasmium1 @m-rit @Atharva-Kanherkar Thank you for your interest! We have already decided that @MiahaCybersec is working on this issue but would appreciate future contributions
